### ISSUE TITLE
Failed to query available provider packages

### ISSUE THREAD

**Issue by mits87** [unfunco/terraform-aws-oidc-github#12]
Hi there!

Thanks for great module!
One small thing, currently when I'm trying to use that module I'm getting this error:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/605186/166809537-3ece3399-36f8-43cb-a24b-0ff73624c257.png">

I guess this is because I'm using older version of `hashicorp/aws` than you:
```
aws = {
  source  = "hashicorp/aws"
  version = "~> 3.74"
}
```

Could you support also version 3.74?

**Comment by unfunco** [comment]
Hello @mits87 – I'll take a look at this later today to see if all the resources are supported and if it's possible, I will publish an update. Thanks!

**Comment by unfunco** [comment]
Hey @mits87 – unfortunately the data resource `aws_iam_openid_connect_provider` requires v4.2.0 or later of the AWS provider and I don't want to break backwards compatibility for other users. Sorry about that.
