### ISSUE TITLE
Two instances of this module in one account conflict due to the same name

### ISSUE THREAD

**Issue by pww217** [unfunco/terraform-aws-oidc-github#23]
It's related to [this](https://github.com/unfunco/terraform-aws-oidc-github/blob/7cffa030a7f9a4d288658aa9495dfa9445c12427/main.tf#L64) resource. The name seems auto-generated and we can't override it as far as I can tell.

**Comment by pww217** [comment]
Error: `Error: creating IAM OIDC Provider: EntityAlreadyExists: Provider with url https://token.actions.githubusercontent.com already exists`

**Comment by pww217** [comment]
Maybe there's nothing that can be done about this, but for RBAC/security reasons using a single Github provider for multiple repos isn't ideal.

**Comment by unfunco** [comment]
Hello @pww217, unfortunately one OIDC provider per URL is a limitation but you can configure multiple roles if that works for you?

More information in this merged pull request:
https://github.com/unfunco/terraform-aws-oidc-github/pull/4

**Comment by pww217** [comment]
Thank you, I had begun to reach that conclusion myself. I'll look into that PR and close this issue. 

Appreciate the response and your useful little module here. Thanks again.
