### ISSUE TITLE
support organization wide (all repos)

### ISSUE THREAD

**Issue by chrisgoffinet** [unfunco/terraform-aws-oidc-github#5]
At the moment you have `github_repositories` which is `list(string)` that supports defining which repos you want the IAM policy for. In some organizations you might want to allowlist all repos by having:

```
    condition {
      test     = "StringLike"
      variable = "token.actions.githubusercontent.com:sub"
      values   = ["repo:myorg/*"]
    }
```
I am happy to submit a PR, but if you think it might be quick, I'll leave it to you.

**Comment by unfunco** [comment]
Hello @chrisgoffinet, I haven't tested this yet but I think this might already be possible with the following:

```terraform
module "aws_oidc_github" {
  source  = "unfunco/oidc-github/aws"
  version = "0.5.0"

  github_organisation = "myorg"
  github_repositories = ["*"]
}
```

**Comment by chrisgoffinet** [comment]
@unfunco good call! :) I verified just now, I was originally thinking using `*` would produce `repo:myorg/*:*` that it wouldn't work. But it does, as now that I remember you can actually adjust `values` to include specific `refs/` if you wanted. So I am closing this out since I tested and it works. Thanks!
